services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - mysql_db
            - postgres_db
        networks:
            - default
        depends_on:
            - mysql_db
            - postgres_db
    mysql_db:
        image: mysql:5.7.13
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default

    postgres_db:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: pDb
            POSTGRES_USER: puser
            POSTGRES_PASSWORD: ptest
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - pdb:/var/lib/postgresql
        ports:
            - 3307:3307

    phpmyadmin:
        image: phpmyadmin
        links: 
            - mysql_db:mysql_db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test

            
volumes:
    persistent:
    pdb:
