version: '3.8'

services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        depends_on:
            - mysql_db
            - postgres_db
        networks:
            - default

    mysql_db:
        image: mysql:5.7.13
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./dump/mysql/myDb.sql:/docker-entrypoint-initdb.d/myDb.sql
            - persistent:/var/lib/mysql
        networks:
            - default
        restart: always

    postgres_db:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: pDb
            POSTGRES_USER: puser
            POSTGRES_PASSWORD: ptest
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./dump/postgres/pDb.sql:/docker-entrypoint-initdb.d/pDb.sql
            - pdb:/var/lib/postgresql/data
        networks:
            - default
        restart: always

    phpmyadmin:
        image: phpmyadmin
        depends_on: 
            - mysql_db
        ports:
            - "8000:80"
        environment:
            PMA_HOST: mysql_db
            MYSQL_ROOT_PASSWORD: test
        networks:
            - default

volumes:
    persistent:
    pdb:
